version: "3"

services:
  db:
    image: mysql:latest
    volumes:
      - /var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: masterpassword
      MYSQL_DATABASE: database
      MYSQL_USER: root
    ports:
      - 3306:3306

  client:
    command: "yarn start"
    depends_on:
      - server
    build: ./client
    volumes:
      - ./client:/project
    ports:
      - 3000:3000
    environment:
      SERVER: http://localhost:1337

  server:
    depends_on:
      - db
    command: "yarn start"
    build: ./server
    volumes:
      - ./server:/project
    ports:
      - 1337:1337
    environment:
      PORT: 1337
      DB_DATABASE: database
      DB_USER: root
      DB_PASSWORD: masterpassword

  nginx:
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client/build:/usr/share/nginx/html
